#!/usr/bin/env node
/**
 * Bundle the WASI runner (runner.ts + wasi.ts) into a single JS string and
 * emit it as `runner.bundle.ts`. The DO-side helper imports the string and
 * ships it as the `mainModule` of a Dynamic Worker via `env.LOADER.get()`.
 *
 * Runs at build time, not at deploy time, so the bundle is checked-in source
 * (deterministic deploys, no install step on the consumer's side).
 */
import { build } from "esbuild";
import { readFileSync, writeFileSync, unlinkSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
const tmp = join(here, ".runner.tmp.js");

await build({
  entryPoints: [join(here, "runner.ts")],
  bundle:      true,
  format:      "esm",
  platform:    "neutral",
  target:      "es2022",
  external:    ["./program.wasm"],   // resolved by the Dynamic Worker loader
  outfile:     tmp,
});

const code = readFileSync(tmp, "utf8");
unlinkSync(tmp);

const stale = join(here, "runner.bundle.js");
if (existsSync(stale)) unlinkSync(stale);

const out =
  `// AUTO-GENERATED by src/worker-sandbox/build.mjs — do not edit.\n` +
  `// Bundled WASI runner used as the mainModule for Dynamic Worker .wasm execution.\n` +
  `export const RUNNER_BUNDLE_JS = ${JSON.stringify(code)};\n`;
writeFileSync(join(here, "runner.bundle.ts"), out);
console.log(`runner.bundle.ts: ${out.length} chars (${(out.length / 1024).toFixed(1)}kb)`);
