#!/usr/bin/env node
/**
 * Build pipeline for @cloudflare/workspace.
 *
 * Emits four artifacts into ./dist:
 *
 *   index.js              — DO-side `Workspace` class + re-exported types
 *   worker-sandbox.js     — `runWasm()` helper for Dynamic Worker execution
 *   container-sandbox.cjs — container-side server (FUSE + capnweb), pre-built
 *                           so consumers just COPY it into their Dockerfile
 *   shared.js             — wire types and the RPC interface
 *
 * The WASI runner bundle (worker-sandbox/runner.bundle.ts) is generated by
 * src/worker-sandbox/build.mjs at edit time and checked into source.
 */
import { build } from "esbuild";
import { mkdirSync, copyFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const src  = join(root, "src");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const common = {
  bundle:   true,
  platform: "neutral",
  target:   "es2022",
  format:   "esm",
  external: [
    // Workers-runtime types — the consumer provides via @cloudflare/workers-types.
    // Mark Cloudflare SDK packages external so consumers' own copies are used.
    "@cloudflare/sandbox",
    "@cloudflare/containers",
    "capnweb",
    // isomorphic-git pulls in a small zoo of CommonJS transitive deps
    // (crc-32, clean-git-ref, diff3, inherits, sha.js). Marking external
    // means the consumer Worker gets one resolved copy via nodejs_compat
    // instead of esbuild trying (and failing) to bundle them under
    // platform:neutral.
    "isomorphic-git",
  ],
};

await build({
  ...common,
  entryPoints: [join(src, "index.ts")],
  outfile:     join(dist, "index.js"),
});
await build({
  ...common,
  entryPoints: [join(src, "worker-sandbox/index.ts")],
  outfile:     join(dist, "worker-sandbox.js"),
});
await build({
  ...common,
  entryPoints: [join(src, "shared/index.ts")],
  outfile:     join(dist, "shared.js"),
});
await build({
  ...common,
  entryPoints: [join(src, "git.ts")],
  outfile:     join(dist, "git.js"),
});

// container-sandbox runs in Node inside the @cloudflare/sandbox image —
// CommonJS, Node platform, fuse-native + ws stay external (npm-installed
// alongside the bundle).
await build({
  entryPoints: [join(src, "container-sandbox/index.ts")],
  outfile:     join(dist, "container-sandbox.cjs"),
  bundle:      true,
  platform:    "node",
  target:      "node20",
  format:      "cjs",
  external:    ["fuse-native", "ws"],
});

// Ship a package.json for the container-sandbox runtime deps so consumers
// can `npm install` it alongside the .cjs in their Docker image.
writeFileSync(join(dist, "container-sandbox.package.json"), JSON.stringify({
  name:    "@cloudflare/workspace-container-sandbox-runtime",
  version: "0.1.0",
  private: true,
  dependencies: {
    "fuse-native": "^2.2.6",
    "ws":          "^8.20.0",
    "capnweb":     "^0.6.1",
  },
}, null, 2));

// Ship a Dockerfile snippet consumers can include/extend.
writeFileSync(join(dist, "container-sandbox.Dockerfile.partial"), [
  "# Workspace container-sandbox: FUSE + capnweb server.",
  "# Add this to your sandbox Dockerfile.",
  "RUN apt-get update && apt-get install -y --no-install-recommends fuse3 libfuse2 ca-certificates && rm -rf /var/lib/apt/lists/*",
  "WORKDIR /app",
  "COPY node_modules/@cloudflare/workspace/dist/container-sandbox.cjs              ./server.cjs",
  "COPY node_modules/@cloudflare/workspace/dist/container-sandbox.package.json     ./package.json",
  "RUN npm install --omit=dev",
  "EXPOSE 4567",
  "",
].join("\n"));

console.log("workspace package built:");
console.log("  dist/index.js");
console.log("  dist/worker-sandbox.js");
console.log("  dist/container-sandbox.cjs");
console.log("  dist/container-sandbox.package.json");
console.log("  dist/container-sandbox.Dockerfile.partial");
console.log("  dist/shared.js");
