// Augments the Wrangler-generated `Env` (worker-configuration.d.ts)
// with bindings and vars that aren't declared in wrangler.jsonc — secrets and
// optional integrations wired in at deploy time or absent in some environments.
//
// `worker-configuration.d.ts` is generated by `wrangler types` and must not be
// hand-edited; add any non-config-declared env member here instead.

// The Worker's runtime env is typed as the global `Env` (which Wrangler
// generates as `interface Env extends __BaseEnv_Env {}`). Merge directly into
// that global interface so `this.env.*` sees these members.
interface Env {
    // Model + provider credentials. Secret / optional overrides.
    OPENAI_API_KEY?: string;
    BRAVE_API_KEY?: string;

    // Cloudflare Access verification (optional; unset in local dev).
    ACCESS_TEAM_DOMAIN?: string; // e.g. "yourteam.cloudflareaccess.com"
    ACCESS_AUD?: string; // Application AUD tag from Access settings
    ACCESS_DEV_USER?: string; // JSON identity for local dev

    // Notification + URL config.
    GCHAT_WEBHOOK_URL?: string; // Google Chat incoming webhook for mention notifications
    APP_BASE_URL?: string; // Public origin used to build absolute URLs

    // R2 S3 credentials for the `assets publish` shell command. Optional; when
    // any is unset the Agent skips wiring the assets client and the command
    // reports "not configured" rather than failing on the presign step.
    R2_ACCESS_KEY_ID?: string;
    R2_SECRET_ACCESS_KEY?: string;
    CLOUDFLARE_ACCOUNT_ID?: string;
    R2_ENDPOINT?: string; // optional override of the account-derived endpoint
}
