// Example Worker + container-enabled Durable Object that runs a
// Workspace inside a Cloudflare Container.
//
// The DO is a thin shell over CloudflareContainerBackend: it picks
// the container (this.ctx.container) and the egress fetcher
// (ctx.exports.WorkspaceProxy bound to this DO instance), forwards
// container-bound /ws upgrades back through the backend, and
// otherwise just calls into a single Workspace instance.
//
// Wire shape:
//
//   client ─► Worker /c/<name>/{file,exec}
//              │  (DO RPC)
//              ▼
//        ContainerExample DO ──► Container ──► wsd (:8080)
//              ▲                                │
//              │  ws://workspace.internal/ws    │
//              └─── capnweb session ◀─────────────┘

import { DurableObject } from "cloudflare:workers";

import {
  CloudflareContainerBackend,
  type DurableObjectStorageLike,
  Workspace,
  WorkspaceProxy,
  type WorkspaceStub,
  withWorkspaceContainer,
} from "@cloudflare/workspace";

// Re-export so the runtime can build a loopback binding for the
// container egress (ctx.exports.WorkspaceProxy below). The class
// itself lives in @cloudflare/workspace; the re-export is what
// puts it in the worker's top-level module graph.
export { WorkspaceProxy };

// Env is generated by `wrangler types` into worker-configuration.d.ts.

// ---------------------------------------------------------------
// Durable Object: owns one Workspace backed by one container.
// ---------------------------------------------------------------
export class ContainerExample extends withWorkspaceContainer(class extends DurableObject<Env> {}) {
  readonly #backend: CloudflareContainerBackend;
  readonly #workspace: Workspace;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.#backend = new CloudflareContainerBackend({
      container: () => this,
      workspace: { binding: "ContainerExample", id: ctx.id.toString() },
    });
    this.#workspace = new Workspace({
      // ctx.storage.sql.exec returns a narrower row type than
      // DurableObjectStorageLike declares; the runtime shape
      // matches. Cast through unknown to bypass invariance.
      storage: ctx.storage as unknown as DurableObjectStorageLike,
      backends: [this.#backend],
    });
  }

  // ---- Worker-facing RPC surface --------------------------------

  // Returns an RpcTarget that the caller (Worker or another DO)
  // uses to reach the Workspace. Methods on the returned stub
  // round-trip back into this DO over Workers RPC; the actual
  // SyncRPC + ShellRPC traffic stays on the wsd ↔ DO capnweb wire.
  async getWorkspace(): Promise<WorkspaceStub> {
    await this.#workspace.ready();
    return this.#workspace.stub();
  }

  // ---- WebSocket: wsd's outbound /ws upgrade ---------------------

  override async fetch(request: Request): Promise<Response> {
    return this.#backend.handleFetch(request);
  }
}

// ---------------------------------------------------------------
// Worker HTTP surface (unchanged)
// ---------------------------------------------------------------

interface ExecRequest {
  command?: string;
  argv?: string[];
  cwd?: string;
  encoding?: "utf8";
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    const fileMatch = url.pathname.match(/^\/c\/([^/]+)\/file\/(.+)$/);
    if (fileMatch) return handleFile(request, env, fileMatch[1], `/${fileMatch[2]}`);

    const execMatch = url.pathname.match(/^\/c\/([^/]+)\/exec\/?$/);
    if (execMatch) return handleExec(request, env, execMatch[1]);

    if (url.pathname === "/" || url.pathname === "") {
      return new Response(
        [
          "wsd-container example",
          "",
          "  PUT  /c/<name>/file/<path>     write file",
          "  GET  /c/<name>/file/<path>     read file",
          "  POST /c/<name>/exec            run a command (JSON result)",

          "",
        ].join("\n"),
        { headers: { "content-type": "text/plain" } },
      );
    }

    return new Response("not found", { status: 404 });
  },
} satisfies ExportedHandler<Env>;

async function handleFile(
  request: Request,
  env: Env,
  name: string,
  path: string,
): Promise<Response> {
  const stub = env.ContainerExample.get(env.ContainerExample.idFromName(name));
  const ws = await stub.getWorkspace();

  if (request.method === "PUT") {
    const body = new Uint8Array(await request.arrayBuffer());
    try {
      await ws.fs.writeFile(path, body);
      return new Response(null, { status: 204 });
    } catch (error) {
      return errorJSON(error, 500);
    }
  }

  if (request.method === "GET") {
    try {
      const stream = await ws.fs.readFile(path, {});
      return new Response(stream, {
        status: 200,
        headers: { "content-type": "application/octet-stream" },
      });
    } catch (error) {
      const code = (error as { code?: string }).code;
      if (code === "ENOENT") return errorJSON(error, 404);
      return errorJSON(error, 500);
    }
  }

  return new Response("method not allowed", { status: 405, headers: { allow: "GET, PUT" } });
}

async function handleExec(request: Request, env: Env, name: string): Promise<Response> {
  if (request.method !== "POST") {
    return new Response("method not allowed", { status: 405, headers: { allow: "POST" } });
  }
  let body: ExecRequest;
  try {
    body = (await request.json()) as ExecRequest;
  } catch {
    return errorJSON(new Error("invalid JSON body"), 400);
  }

  let command: string;
  if (typeof body.command === "string" && body.command.length > 0) {
    command = body.command;
  } else if (Array.isArray(body.argv) && body.argv.length > 0) {
    command = body.argv.map(shellQuote).join(" ");
  } else {
    return errorJSON(new Error("must provide command or argv"), 400);
  }

  const stub = env.ContainerExample.get(env.ContainerExample.idFromName(name));
  const ws = await stub.getWorkspace();
  try {
    const handle = await ws.shell.exec(command, { cwd: body.cwd, encoding: "utf8" });
    const result = await handle.result();
    return new Response(JSON.stringify(result), {
      status: 200,
      headers: { "content-type": "application/json" },
    });
  } catch (error) {
    return errorJSON(error, 500);
  }
}

function errorJSON(error: unknown, status: number): Response {
  const message = error instanceof Error ? error.message : String(error);
  const code = (error as { code?: string }).code;
  return new Response(JSON.stringify({ error: message, code }), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function shellQuote(arg: string): string {
  if (/^[A-Za-z0-9_\-+=:,./@%]+$/.test(arg)) return arg;
  return `'${arg.replace(/'/g, "'\\''")}'`;
}
